{{- if .Values.awsSecrets -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "application.secretsProviderName" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
spec:
  parameters:
    objects: |
      {{- range $k, $v := .Values.awsSecrets }}
      - objectAlias: {{ $k | quote }}
        objectType: "secretsmanager"
        objectName: {{ $v | quote  }}
      {{- end }}
      
  provider: aws
  secretObjects:
    - data:
       {{- range $k, $v := .Values.awsSecrets }}
        - key: {{ $k | quote }}
          objectName: {{ $k | quote }}
        {{- end }}
      secretName: {{ include "application.secretsProviderName" . }}
      type: Opaque
{{- end -}}