{{- if .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.service.servicePorts }}
    {{- if .service_disabled -}}
    {{- else }}
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
{{- end }}