name: Smart Contract Artifact Build

on:
  push: 
    branches: 
      - main
    paths:
      - "task2/**"  

env:
  DEPLOY_DIR: "task2/"
  ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}

jobs:
  build: 
    name: Deploy HardHat
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x 

    - name: Deploy Contract
      run: |
        cd $DEPLOY_DIR
        npm install
        npx hardhat compile
        npx hardhat run scripts/deploy.js --network kovan

    - name: Test SmartContract
      run: |
        cd $DEPLOY_DIR
        npx hardhat test